# Generated by Django 5.2.7 on 2025-10-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HumiditySensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ProximitySensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TemperatureSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="VibratorSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(editable=False)),
                ("value", models.BooleanField()),
            ],
        ),
    ]
