# Generated by Django 5.2.7 on 2025-11-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HumiditySensor',
        ),
        migrations.DeleteModel(
            name='TemperatureSensor',
        ),
        migrations.DeleteModel(
            name='VibratorSensor',
        ),
        migrations.AddField(
            model_name='proximitysensor',
            name='name',
            field=models.CharField(default='Lavender', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proximitysensor',
            name='value',
            field=models.BooleanField(),
        ),
    ]
